accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
    path('<int:article_pk>/bookmark/', views.bookmark, name='bookmark'),
    path('<int:article_pk>/comments/<int:comment_pk>/likes/', views.comment_likes, name='comment_likes'),
    path('<int:article_pk>/comments/<int:comment_pk>/dislikes/', views.comment_dislikes, name='comment_dislikes'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('search/', views.search, name='search'),
    # 태그 목록을 볼 수 있는 url 
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    # 태그가 달린 객체들의 목록
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    # path('<int:article_pk>/comments/<int:comment_pk>/update/', views.replyUpdate, name='replyUpdate'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('articles/', include('articles.urls')),
    path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('search/', views.search, name='search'),
    path('region/<region_name>', views.region, name='region'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/likes/', views.post_likes, name='post_likes'),
    path('<int:post_pk>/comment/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_pk>/comment/<int:comment_pk>/likes/', views.comment_likes, name='comment_likes'),
    
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    # 태그가 달린 객체들의 목록
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import os

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField('self', symmetrical=False, related_name='following')
    def profile(instance, filename):
        return f'profiles/{instance.username}/{filename}'
    profile_image = ProcessedImageField(blank=True,
                                upload_to = profile,
                                processors= [ResizeToFill(300, 300)],
                                format='JPEG',
                                options={'quality' : 80},
                                )
    def delete(self, *args, **kargs):
        if self.profile_image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.profile_image.path))      
        super(User, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_user = User.objects.get(id=self.id)
            if self.profile_image != old_user.profile_image:
                if old_user.profile_image:
                    os.remove(os.path.join(settings.MEDIA_ROOT, old_user.profile_image.path))
        super(User, self).save(*args, **kwargs)

    birthday = models.DateField(null=True, blank=True)
    mbti = models.TextField(null=True, blank=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import get_user_model

class Birthday(forms.DateInput):
    input_type = 'date'


class CustomUserUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'birthday', 'email', 'profile_image', 'mbti',)
    username = forms.CharField(
        required=True,
        label='ID',
        widget= forms.TextInput(
          attrs = {
            'class' : 'form-control',
            'placeholder' : '영문 소문자 또는 영문 대문자, 숫자 조합 6~12 자리',
          }
        )
    )
    first_name = forms.CharField(
        required=True,
        label='FirstName',
        widget= forms.TextInput(
          attrs = {
            'class' : 'form-control',
            'placeholder' : '이름을 입력하세요.',
          } 
        )
    )
    last_name = forms.CharField(
        required=True,
        label='LastName',
        widget= forms.TextInput(
          attrs = {
            'class' : 'form-control',
            'placeholder' : '성을 입력하세요.',
          }
        )
    )
    email = forms.EmailField(
        required=True,
        label='Email',
        widget= forms.EmailInput(
          attrs = {
            'class' : 'form-control',
            'placeholder' : 'Email 입력',
          }
        )
    )
    password1 = forms.CharField(
        required=True,
        label='Password1',
        widget= forms.PasswordInput(
          attrs = {
            'class' : 'form-control',
            'placeholder' : '영문, 숫자, 특수문자(~!@#$%^&*) 조합 8~15 자리',
          }
        )
    )
    password2 = forms.CharField(
        required=True,
        label='Password2',
        widget= forms.PasswordInput(
          attrs = {
            'class' : 'form-control',
            'placeholder' : '영문, 숫자, 특수문자(~!@#$%^&*) 조합 8~15 자리',
          }
        )
    )
    profile_image = forms.ImageField(
        required=False,
        label='Profile_image',
        widget= forms.ClearableFileInput(
          attrs = {
            'class' : 'form-control',
          }
        )
    )
    mbti = forms.CharField(
        required=False,
        label='mbti',
        widget= forms.TextInput(
          attrs = {
            'class' : 'form-control',
            'placeholder' : 'mbti',
          }
        )
    )
    birthday = forms.DateField(
        required=False,
        label='Birthday',
        input_formats=['%Y-%m-%d'],
        widget= Birthday(
          attrs = {
            'class' : 'form-control',
            'placeholder' : '생년월일',
          }
        )
    )


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        max_length=30,
        required=True,
        label='ID',
        widget= forms.TextInput(
          attrs = {
              'class' : 'form-control',
              'placeholder' : 'ID 입력',
          }
        )
    )
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(
          attrs={
            'class' : 'form-control',
            'placeholder' : 'Password 입력',
          }
        )
    )

class Birthday(forms.DateInput):
    input_type = 'date'

class CustomUserChangeForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].help_text = ''
        
    class Meta(UserChangeForm):
        model = get_user_model()
        fields = ('first_name', 'last_name', 'mbti', 'birthday', 'email', 'profile_image',)
    first_name = forms.CharField(
        required=True,
        label='FirstName',
        widget= forms.TextInput(
          attrs = {
            'class' : 'form-control',
            'placeholder' : '성을 입력하세요.',
          } 
        )
    )
    last_name = forms.CharField(
        required=True,
        label='LastName',
        widget= forms.TextInput(
          attrs = {
            'class' : 'form-control',
            'placeholder' : '이름을 입력하세요.',
          }
        )
    )
    email = forms.EmailField(
        required=True,
        label='Email',
        widget= forms.EmailInput(
          attrs = {
            'class' : 'form-control',
            'placeholder' : 'Email 입력',
          }
        )
    )
    profile_image = forms.ImageField(
        required=False,
        label='Profile_image',
        widget= forms.ClearableFileInput(
          attrs = {
            'class' : 'form-control',
          }
        )
    )
    mbti = forms.CharField(
        required=False,
        label='mbti',
        widget= forms.TextInput(
          attrs = {
            'class' : 'form-control',
            'placeholder' : 'mbti',
          }
        )
    )
    birthday = forms.DateField(
        required=False,
        label='Birthday',
        input_formats=['%Y-%m-%d'],
        widget= Birthday(
          attrs = {
            'class' : 'form-control',
            'placeholder' : '생년월일',
          }
        )
    )




class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="기존 비밀번호",
        widget=forms.PasswordInput(
        attrs={
            'class' : 'form-control',
            'placeholder' : '기존 비밀번호 입력'
        })
    )
    new_password1 = forms.CharField(
        required=True,
        label='Password1',
        widget= forms.PasswordInput(
          attrs = {
            'class' : 'form-control',
            'placeholder' : '새 비밀번호(영문, 숫자, 특수문자(~!@#$%^&*) 조합 8~15 자리)',
          }
        )
    )
    new_password2 = forms.CharField(
        required=True,
        label='Password2',
        widget= forms.PasswordInput(
          attrs = {
            'class' : 'form-control',
            'placeholder' : '새 비밀번호 다시 입력',
          }
        )
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, logout as auth_logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import CustomPasswordChangeForm, CustomAuthenticationForm, CustomUserChangeForm, CustomUserUserCreationForm
from django.contrib.auth import get_user_model
from posts.models import Post
from articles.models import Article
from django.http import JsonResponse


# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:index')
    else:
        form = CustomAuthenticationForm()
    return render(request, 'accounts/login.html', {'form' : form})


@login_required
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('posts:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
    if request.method == 'POST':
      form = CustomUserUserCreationForm(request.POST, request.FILES)
      if form.is_valid():
          user = form.save()
          user.backend = 'django.contrib.auth.backends.ModelBackend'
          auth_login(request, user)
          return redirect('posts:index')
    else:
        form = CustomUserUserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('posts:index')



@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', username=request.user.username)
    else:
        form = CustomUserChangeForm(instance=request.user)
    return render(request, 'accounts/update.html', {'form' : form})



@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('posts:index')
    else:
        form = CustomPasswordChangeForm(request.user)
    return render(request, 'accounts/password.html', {'form':form})


def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    posts = Post.objects.filter(user=person).order_by('-pk') 
    articles = Article.objects.filter(user=person).order_by('-pk') 
    
    print(posts,articles)

    context = {
        'person' : person,
        'posts' : posts,
        'articles' : articles,
    }
    return render(request, 'accounts/profile.html', context)

@login_required
def follow(request, user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)

    if person != request.user:
        if request.user in person.followers.all():
            person.followers.remove(request.user)
            is_followed = False
        else:
            person.followers.add(request.user)
            is_followed = True
        context ={
            'is_followed': is_followed,
            'followings_count' : person.following.count(),
            'followers_count' : person.followers.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:profile', person.username)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load socialaccount %}

{% block header %}
<link rel="stylesheet" href="{% static 'style/accounts/login.css' %}">
{% endblock header %}

{% block style %}
<style>
</style>
{% endblock style %}

{% block content %}
{% load static %}
  <article class="main--article--container">
    <div class="main--accounts--section--container">
      <section class="section--form--wrap">
        <div class="main--login">
          <img class="" src="{% static 'img/triptopper_c_logo_01.png' %}" alt="image">
        </div>
        <h2>Log in</h2>
        <form class="d-grid main--login--form" action="{% url 'accounts:login' %}" method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="log in" class="btn btn-success">
        </form>
      </section>
      <hr>
      <section class="d-grid">
        <a type="button" class="btn btn-warning" href="{% provider_login_url 'kakao' method='oauth2' %}">
          KakaoTalk Sign up
        </a>
      </section>
      <section class="d-grid mt-2">
        <a  type="button" class="btn btn-success" href="{% provider_login_url 'naver'%}">
          NAVER Log in
        </a>
      </section>
    </div>
  </article>
{% endblock content %}
{% block javascript %}
{% endblock javascript %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'style/accounts/login.css' %}">
<link rel="stylesheet" href="{% static 'style/articles/common.css' %}">
{% endblock header %}


{% block content %}
<article class="main--article--container">
  <section class="section--form--wrap">
    <div class="main--login">
      <img class="" src="{% static 'img/triptopper_c_logo_01.png' %}" alt="image">
    </div>
    <hr>
    <h2>비밀번호 변경</h2>
    <form action="{% url 'accounts:change_password' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      {{ form.non_field_errors }}
      <div class="d-grid">
        <button type="submit" class="btn btn-success">등록</button>
      </div>
    </form>
  </section>
</article>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}


{% block header %}
<link rel="stylesheet" href="{% static 'style/accounts/profile.css' %}">
<link rel="stylesheet" href="{% static 'style/articles/common.css' %}">
{% endblock header %}

{% block content %}
<article class="main--article--container">
  <h1>{{ person }}님의 Profile</h1>
  <section class="profile--user--container">
    <div class="profile--user--wrap">
      <div class="profile--image--wrap">
        {% if person.profile_image %}
        <img src="{{ person.profile_image.url }}" alt="profile-image">
        {% else %}
        <i class="bi bi-person-circle"></i>
        {% endif %}    
      </div>
      <div class="profile--info--wrap">
        <ul class="profile--info">
          <li>
            <p>ID</p>
            <p>{{ person.username }}</p>
          </li>
          <li>
            <p>FIRST NAME</p>
            <p>{{ person.first_name }}</p>
          </li>
          <li>
            <p>LAST NAME</p>
            <p>{{ person.last_name }}</p>
          </li>
          <li>
            <p>MBTI</p>
            <p>{{ person.mbti }}</p>
            </li>
          <li>
            <p>BIRTHDAY</p>
            <p>{{ person.birthday }}</p>
          </li>
          <li>
            <p>E-MAIL</p>
            <p>{{ person.email }}</p>
          </li>
          <li>
            <p>Following </p>
            <p id="followings-count">  {{person.following.all|length}} </p>
            <p>Follower </p>
            <p id="followers-count"> {{person.followers.all|length}}</p>
          </li>
        </ul>

      </div>
    </div>
    <div class="d-grid profile--update--wrap">
      <a class="btn btn-success " type="button" href="{% url 'accounts:update'%}">profile 수정</a>
    </div>
    <div>
      {% if request.user != person %}
        <form id='follow-form' data-user-id="{{ person.pk }}">
          {% csrf_token %}
          {% if request.user in person.followers.all %}         
            <input type="submit" value="Unfollow" class="btn btn-success"> 
            {% else %}
            <input type="submit" value="Follow" class="btn btn-success w-100 mt-3"> 
          {% endif %}
        </form>
      {% endif %} 
    </div>
  </section>
  <section class="profile--posts--container">
    <h3>Posts</h3>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">No</th>
          <th scope="col">제목</th>
          <th scope="col">글쓴이</th>
          <th scope="col">작성시간</th>
          <th scope="col">조회수</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for post in posts %}
        <tr>
          <th scope="row">{{ post.pk }}</th>
          <td><a href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a></td>
          <td>{{ post.user }}</td>
          <td>{{ post.created_at }}</td>
          <td>{{ post.views.all|length }}</td>
        </tr>
        {% endfor %}
      </tbody>    
    </table>
  </section>
  <section class="profile--articles--container">
    <h3>Community</h3>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">No</th>
          <th scope="col">제목</th>
          <th scope="col">글쓴이</th>
          <th scope="col">작성시간</th>
          <th scope="col">조회수</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for article in articles %}
        <tr>
          <th scope="row">{{ article.pk }}</th>
          <td><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></td>
          <td>{{ article.user }}</td>
          <td>{{ article.created_at }}</td>
          <td>{{ article.views.all|length }}</td>
        </tr>
        {% endfor %}
      </tbody>    
    </table>
  </section>
  <section class="profile--articles--container">
    <h3>Bookmark</h3>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">No</th>
          <th scope="col">제목</th>
          <th scope="col">글쓴이</th>
          <th scope="col">작성시간</th>
          <th scope="col">조회수</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for article in person.bookmark_articles.all %}
        <tr>
          <th scope="row">{{ article.pk }}</th>
          <td><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></td>
          <td>{{ article.user }}</td>
          <td>{{ article.created_at }}</td>
          <td>{{ article.views.all|length }}</td>
        </tr>
        {% endfor %}
        {% for post in person.bookmark_posts.all %}
        <tr>
          <th scope="row">{{ post.pk }}</th>
          <td><a href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a></td>
          <td>{{ post.user }}</td>
          <td>{{ post.created_at }}</td>
          <td>{{ post.views.all|length }}</td>
        </tr>
        {% endfor %}
      </tbody>    
    </table>
  </section>

</article>
{% endblock content %}

{% block javascript %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'js/accounts-profile.js' %}"></script>
{% endblock javascript %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load socialaccount %}
{% block header %}
<link rel="stylesheet" href="{% static 'style/accounts/login.css' %}">
{% comment %} <link rel="stylesheet" href="{% static 'style/accounts/common.css' %}"> {% endcomment %}
{% endblock header %}

{% block content %}
    <article class="main--article--container">
      <div class="main--accounts--section--container">
        <section class="section--form--wrap">
          <div class="main--login">
            <img class="" src="{% static 'img/triptopper_c_logo_01.png' %}" alt="image">
          </div>
          <h2>Sign up</h2>
          <form class="d-grid main--login--form" action="{% url 'accounts:signup' %}" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
            <input type="submit" value="sign up" class="btn btn-success">
          </form>
        </section>
        <hr>
        <section class="d-grid">
          <a  type="button" class="btn btn-warning" href="{% provider_login_url 'kakao' method='oauth2' %}">
            KakaoTalk Sign up
          </a>
        </section>
        <section class="d-grid mt-2">
          <a  type="button" class="btn btn-success" href="{% provider_login_url 'naver'%}">
            NAVER Sign up
          </a>
        </section>
      </div>
    </article>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block style %}
<style>
</style>
{% endblock style %}

{% block content %}
<h2>프로필 수정 페이지</h2>
<form action="{% url 'accounts:update' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {{ form.non_field_errors }}
    <input type="submit" value="프로필 수정">
</form>
{% endblock content %}