accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
    path('<int:article_pk>/bookmark/', views.bookmark, name='bookmark'),
    path('<int:article_pk>/comments/<int:comment_pk>/likes/', views.comment_likes, name='comment_likes'),
    path('<int:article_pk>/comments/<int:comment_pk>/dislikes/', views.comment_dislikes, name='comment_dislikes'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('search/', views.search, name='search'),
    # 태그 목록을 볼 수 있는 url 
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    # 태그가 달린 객체들의 목록
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    # path('<int:article_pk>/comments/<int:comment_pk>/update/', views.replyUpdate, name='replyUpdate'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('articles/', include('articles.urls')),
    path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.conf import settings
from datetime import datetime, timedelta
from django.utils import timezone
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from taggit.managers import TaggableManager
from django.urls import reverse
import os


# Create your models here.

class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    bookmark_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='bookmark_articles')
    views = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='view_articles')
    tags = TaggableManager(blank=True)
    
    def get_absolute_url(self):
        return reverse('articles:detail', args=[int(self.id)])


    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.strftime('%Y-%m-%d')


class ArticleImage(models.Model):
    article = models.ForeignKey(Article, null=True, blank=True, on_delete=models.CASCADE)

    def article_image_path(instance, filename):
        return f'articles/{instance.article.pk}/{filename}'
           
    image = ProcessedImageField(blank=True,
                                upload_to = article_image_path,
                                processors= [ResizeToFill(200, 200)],
                                format='JPEG',
                                options={'quality' : 90},
                                null = True,
                                )
    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.name))
            dir_path = os.path.dirname(os.path.join(settings.MEDIA_ROOT, self.image.name))
            if not os.listdir(dir_path):
                os.rmdir(dir_path)
        super(ArticleImage, self).delete(*args, **kargs)


class ArticleComment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comment')
    dislike_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='dislike_comments')

    
    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at
        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.strftime('%Y-%m-%d')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, ArticleComment, ArticleImage
from .forms import ArticleForm, ArticleCommentForm , ArticleImageForm, DeleteArticleImageForm
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, TemplateView
from django.db.models import Q, Count
from django.http import JsonResponse


# Create your views here.
 

def index(request):
    articles = Article.objects.all()
    if request.method == 'GET':
        order = request.GET.get('order')
        if order == "2":
            articles = articles.annotate(like_count=Count('like_users')).order_by('-like_count', '-pk')
        elif order == "3":
            articles = articles.annotate(view_count=Count('views')).order_by('-view_count', '-pk')
        else:
            articles = articles.order_by('-pk')
    else:
        articles = articles.order_by('-pk')
    
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        images = request.FILES.getlist('image')
        tags = request.POST.get('tags').split(',')
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            for tag in tags:
                article.tags.add(tag.strip())
            for i in images:
                ArticleImage.objects.create(article=article, image=i)
            return redirect('articles:index')       
        else:
            print(form.errors)
    else:
        form = ArticleForm()
        imageform = ArticleImageForm()
    context = {
        'form': form,
        'imageform' : imageform

    }
    return render(request, 'articles/create.html', context)


# view
def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    comments = article.articlecomment_set.all()[::-1]
    tags = article.tags.all()
    comment_form = ArticleCommentForm()
    context = {
            'article': article,
            'comment_form' : comment_form,
            'comments' : comments,
            'tags' : tags
        }
    if request.user.is_authenticated:
        if request.user not in article.views.all():
            article.views.add(request.user)
    return render(request, 'articles/detail.html', context)


@login_required
def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.user == article.user:
        article.delete()
    return redirect('articles:index')


# @login_required
# def update(request, article_pk):
#     article = Article.objects.get(pk=article_pk)
#     if request.user == article.user:
#         if request.method == 'POST':
#             form = ArticleForm(request.POST, instance=article)
#             images = request.FILES.getlist('image')
#             delete_images_form = DeleteArticleImageForm(request.POST)
#             imageform = ArticleImageForm(request.POST, request.FILES, instance=article)
#             if form.is_valid() and delete_images_form.is_valid(): 
#                 form.save()
#                 article.tags.clear()
#                 tags = request.POST.get('tags').split(',')
#                 for tag in tags:
#                     article.tags.add(tag.strip())
#                 for i in images:
#                     ArticleImage.objects.create(article=article, image=i)
#                 # for delete_image in delete_images_form.cleaned_data['delete_images']:
#                 #     delete_image.delete()
#                 delete_images_form.save()
#                 return redirect('articles:detail', article.pk)
            
#         else:
#             initial_tags = ', '.join(article.tags.all().values_list('name', flat=True))
#             form = ArticleForm(instance=article, initial={'tags': initial_tags})
#             imageform = ArticleImageForm(instance=article)
#             delete_images_form = DeleteArticleImageForm(instance=article)

#     context = {
#         'form': form,
#         'article': article,
#         'imageform': imageform,
#         'delete_images_form': delete_images_form
#     }
#     return render(request, 'articles/update.html', context)


@login_required
def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            images = request.FILES.getlist('image')
            delete_images_form = DeleteArticleImageForm(request.POST)
            imageform = ArticleImageForm(request.POST, request.FILES, instance=article)
            if form.is_valid(): 
                form.save()
                article.tags.clear()
                tags = request.POST.get('tags').split(',')
                for tag in tags:
                    article.tags.add(tag.strip())
                for i in images:
                    ArticleImage.objects.create(article=article, image=i)
                if delete_images_form.is_valid():
                    delete_images_form.save()
                return redirect('articles:detail', article.pk)
            else:
                print(form.errors)
        else:
            initial_tags = ', '.join(article.tags.all().values_list('name', flat=True))
            form = ArticleForm(instance=article, initial={'tags': initial_tags})
            imageform = ArticleImageForm(instance=article)
            delete_images_form = DeleteArticleImageForm(instance=article)

    context = {
        'form': form,
        'article': article,
        'imageform': imageform,
        'delete_images_form': delete_images_form
    }
    return render(request, 'articles/update.html', context)



@login_required
def comment_create(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    comment_form = ArticleCommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        # context = {
        #     'author': comment.user.username,
        #     'created': comment.created_string,
        #     'content': comment.content,
        # }
        return redirect('articles:detail', article_pk)
        # return JsonResponse(context)

    context = {
        'article' : article,
        'comment_form' : comment_form
    }
    return render(request, 'articles/detail.html', context)




@login_required
def likes(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if article.like_users.filter(pk=request.user.pk).exists():
        article.like_users.remove(request.user)
        is_liked = False
    else:
        article.like_users.add(request.user)
        is_liked = True
    likes_count = article.like_users.all().count()
    context = {
        'is_liked' : is_liked,
        'likes_count' : likes_count,
    }
    return JsonResponse(context)


@login_required
def bookmark(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if article.bookmark_user.filter(pk=request.user.pk).exists():
        article.bookmark_user.remove(request.user)
        isbookmarked = False
    else:
        article.bookmark_user.add(request.user)
        isbookmarked = True
    bookmark_count = article.bookmark_user.all().count()
    context = {
        'isbookmarked' :  isbookmarked,
        'bookmark_count' : bookmark_count
    }
    return JsonResponse(context)
    # return redirect('articles:detail', article_pk)


@login_required
def comment_likes(request, article_pk, comment_pk):
    comment = ArticleComment.objects.get(pk=comment_pk)
    if comment.like_users.filter(pk=request.user.pk).exists():
        comment.like_users.remove(request.user)
        r_is_liked = False
    else:
        comment.like_users.add(request.user)
        r_is_liked = True
    r_likes_count = comment.like_users.all().count()
    context = {
        'r_is_liked' : r_is_liked,
        'r_likes_count' : r_likes_count,
    }
    return JsonResponse(context)
    # return redirect('articles:detail', article_pk)


@login_required
def comment_dislikes(request, article_pk, comment_pk):
    comment = ArticleComment.objects.get(pk=comment_pk)
    if comment.dislike_user.filter(pk=request.user.pk).exists():
        comment.dislike_user.remove(request.user)
        dis_is_liked = False
    else:
        comment.dislike_user.add(request.user)
        dis_is_liked = True
    dislikes_count = comment.dislike_user.all().count()
    context = {
        'dis_is_liked' : dis_is_liked,
        'dislikes_count' : dislikes_count,
    }
    return JsonResponse(context)
    # return redirect('articles:detail', article_pk)



@login_required
def comment_delete(request, article_pk, comment_pk):
    comment = ArticleComment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('articles:detail', article_pk)


def search(request):
    query = request.GET.get('q', '')
    if query:
        search = Article.objects.filter(
            Q(title__icontains=query)|
            Q(user__username__exact=query)
        )
    else:
        search = Article.objects.all()[::-1] 
    return render(request, 'articles/index.html', {'articles':search, 'app':'articles'})


class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'

class TaggedObjectLV(ListView):
    template_name = 'taggit/taggit_article_list.html'
    model = Article

    def get_queryset(self):
        return Article.objects.filter(tags__name=self.kwargs.get('tag'))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context
    
# def replyUpdate(request, article_pk, comment_pk):

articles/templates/articles/create.html
{% extends "base.html" %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'style/articles/create.css' %}">
{% endblock header %}

{% block content %}
<article class="main--article--container">
  <div class="article--title--wrap">
    <h3 class="article--title">
      <a href="{% url 'articles:index' %}">Community</a>
    </h3>
    <a class="article--list" href="{% url 'articles:tag_cloud' %}">Tag Cloud</a> 
  </div>
  <div class="card--style--wrap">
    <form action="{% url 'articles:create' %}" method="POST" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      {{ imageform.as_p }}
      {% comment %} {% for field in form %}
        {{field}} <br />
      {% endfor %}
      {% for form in imageform %}
        {{form}}
      {% endfor %} {% endcomment %}
      <div class="d-grid">
        <input class="btn btn-success " type="submit" value="등록"></div>
    </form>
  </div> 
</article>

{% endblock content %}

articles/templates/articles/detail.html
{% extends "base.html" %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'style/articles/detail.css' %}">
<link rel="stylesheet" href="{% static 'style/articles/common.css' %}">
{% endblock header %}

{% block content %}
<article class="main--article--container">
  <div class="article--title--wrap">
    <h3 class="article--title">
      <a href="{% url 'articles:index' %}">Community</a>
    </h3>
    <a class="article--list" href="{% url 'articles:tag_cloud' %}">Tag Cloud</a> 
  </div>
  <section class="board--container card--style--wrap">
    <div class="board--wrap">
      <div class="board--title--user--wrap" >
        <h3 class="board-title">{{ article.title }}</h3>
        <a href="{% url 'accounts:profile' article.user %}">
          <div class="success--underline">
            <div>
              <p class="board--user">
                <span>{{ article.user }}</span>
                <i class="board--mbti">{{ article.user.mbti }}</i>
              </p>
            </div>
            <div class="profile--image--wrap">
              {% if article.user.profile_image %}
              <img class="board--profile--image" src="{{ article.user.profile_image.url }}" alt="profile-image">
              {% else %}
              <img class="board--profile--image" src="{% static 'img/cat_01.png' %}" alt="profile">
              {% endif %}
            </div>
          </div>
        </a>
      </div>
      <hr>
      <div class="board--date--wrap">
        <p>{{ article.created_at }}</p>
        <i class="board--update--date">({{ article.updated_at }})</i>
      </div>
      <div class="board--content">{{ article.content }}</div>
      <div>
        {% for image in article.articleimage_set.all %}
          <img class="board--image--card" src="{{image.image.url}}" alt="img">
        {% endfor %}
      </div>
      <div class="tag--box--wrap">
        {% load taggit_templatetags2_tags %}
        {% get_tags_for_object article as "tags" %}
        {% if tags %}
          {% for tag in tags %}
            {% if tag.name %}
            <a class="tag--box" href="{% url 'articles:tagged_object_list' tag.name %}">{{tag.name}}</a>
            {% endif %}
          {% endfor %}
        {% endif %}
      </div>
      <div class="like--update--container">
        <div class="view--bookmark--like--wrap form--wrap--flex">
          <p>
            <i class="bi bi-eye-fill margin--right">
            {{ article.views.all|length }}</i>
          </p>
          <div class="form--wrap--flex margin--right">
            <form class='bookmark_forms'  data-article-id="{{ article.pk }}">
              {% csrf_token %}
              {% comment %}
              {% if request.user in article.bookmark_user.all %}
                <input type="submit" value='bookmark 취소' id='bookmark-{{article.pk}}'>
              {% else %}
                <button type="submit"><i class="bi bi-star-fill warning--icon"></i></button>
              {% endif %}
              {% endcomment %}
              <button type="submit" id='bookmark-{{article.pk}}>'<i class="bi bi-bookmark-fill success--color"></i></button>
            </form>
            <span id='bookmark-count'> {{article.bookmark_user.all|length}} </span>       
          </div>


          <div class="form--wrap--flex">
            <form class='like_forms' data-article-id="{{ article.pk }}">
              {% csrf_token %}
              {% comment %}
              {% if request.user in article.like_users.all %}
              <input type="submit" value='싫어요' id='like-{{ article.pk }}'>
              {% else %}
              <input type="submit" value='좋아요' id='like-{{ article.pk }}'>
              {% endif %}
              {% endcomment %}
              <button type="submit"  id='like-{{ article.pk }}'><i class="bi bi-heart-fill danger--color"></i></button>
            </form>
            <span id='likes-count'> {{ article.like_users.all|length }} </span>          
          </div>
        </div>
        {% if request.user == article.user %}
        <div class="update--delete--wrap">
          <a class="margin--right primary--underline" href="{% url 'articles:update' article.pk %}">Update</a>
          <a class="danger--underline" onclick="return confirm('게시글을 삭제하시겠습니까?')" href="{% url 'articles:delete' article.pk %}">Delete</a>
        </div>
        {% endif %}
      </div>
    </div>
  </section>
  <section class="comment--container">
    <div>
      <div class="comment--title--wrap">
        <h5>Comment</h5>
        <div>
          {% if comments.all|length > 0 %}
          ( {{ comments.all|length }}  )
          {% endif %}
        </div>
      </div>
      <div>
        {% for comment in comments %}
        <div class="card--style--wrap card--style--wrap">
          <div class="comment--user--delete--wrap">
            <p>
              <a href="{% url 'accounts:profile' comment.user.username %}" class="text-decoration-none text-dark">
                <span class="comment--profile--image--wrap">
                  {% if comment.user.profile_image %}
                  <img class="comment--profile--image" src="{{ comment.user.profile_image.url }}" alt="profile-image">
                  {% else %}
                  <img class="comment--profile--image" src="{% static 'img/user_profile.png' %}" alt="profile">
                  {% endif %}
                </span>
                <span class="success--underline">{{ comment.user }}</span>
              </a>
            </p>
            <div>
              {% if comment.user == request.user %}
              <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method='POST'>
                {% csrf_token %}
                <button type='submit'>
                  <i class="bi bi-x-lg secondary--color"></i>
                </button>
              </form> 
              {% comment %} <input type="button" value="수정" onclick="replyUpdate({{comment.pk}})" class="tdReplyUpdate{{comment.pk}}">
              <input type="button" value="삭제" onclick="replyDelete({{comment.pk}})" class="tdReplyDelete{{comment.pk}}">
              <input type="button" value="진짜 수정" onclick="replySubmit({{comment.pk}})" class="tdReplySubmit{{comment.pk}}" style="display:none">
              <input type="button" value="취소" onclick="replyUpdateCancel({{comment.pk}})" class="tdReplyUpdateCancel{{comment.pk}}" style="display:none"> {% endcomment %}

              {% endif %}
            </div>
          </div>
          <hr>
          {% comment %} <div><input type="text" class="replyContent{{ comment.id }}" value="{{ comment.content }}" style = 
            'width: 100%; outline: 1px solid #cccccc; border:1px solid #ffffff; border-radius:5px; padding:1rem;' readonly ></div> {% endcomment %}
          <div class="comment--content">{{ comment.content }}</div>
          <div class="comment--date--like--wrap">
            <div class="form--wrap--flex">
              <div class="margin--right"><i class="comment--date">{{ comment.created_string }}</i></div>
              <div class="form--wrap--flex margin--right">       
                <form class="comment_like_forms" id="like-form-{{comment.pk}}" data-article-id="{{article.pk}}" data-comment-id="{{comment.pk}}">
                  {% csrf_token %}
                  <button type="submit" id='like-{{ comment.pk }}' {% if request.user in comment.dislike_user.all %} disabled {% endif %}>
                    <i class="bi bi-hand-thumbs-up-fill warning--color"></i>
                  </button>
                </form>
                <p id="r_likes_count_{{comment.pk}}"> {{comment.like_users.all|length}} </p>        
              </div>
              <div class="form--wrap--flex">
                <form class="comment_dislike_forms" id="dislike-form-{{comment.pk}}" data-article-id="{{article.pk}}" data-comment-id="{{comment.pk}}">
                  {% csrf_token %}
                    <button type="submit" id='dislike-{{ comment.pk }}' {% if request.user in comment.like_users.all %} disabled {% endif %} >
                    <i class="bi bi-hand-thumbs-down-fill warning--color"></i>
                  </button>
                </form>
                <p id="dislikes_count_{{comment.pk}}"> {{ comment.dislike_user.all|length }} </p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <div>
        <form action="{% url 'articles:comment_create' article.pk %}" method="POST">
          {% csrf_token %}
          <div class="comment--create--form">
            <p>{{ comment_form.content }}</p>
            <button type="submit" class="comment--create--button">등록</button>
          </div>
        </form>
        {% comment %} <form class="comment-form" id="comment_form">
        {% csrf_token %}
        <div class="input-group mb-3">
          {{ comment_form.content }}
          <button id="comment-submit" type="submit" class="btn btn-outline-warning">댓글 작성</button>
        </div>
        </form> {% endcomment %}
      </div>
    </div>
  </section>
</article>
{% endblock content %}


{% block javascript %}
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'js/articles-detail.js' %}"></script>


{% endblock javascript %}

articles/templates/articles/index.html
{% extends "base.html" %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'style/articles/index.css' %}">
<link rel="stylesheet" href="{% static 'style/articles/common.css' %}">
{% endblock header %}

{% block content %}
<article class="main--article--container">
  <div class="article--title--wrap">
    <h3 class="article--title">
      <a href="{% url 'articles:index' %}">Community</a>
    </h3>
    <a class="article--list" href="{% url 'articles:tag_cloud' %}">Tag Cloud</a> 
  </div>
  <div class="card--style--wrap">
    <div class='d-flex justify-content-between my-1'>
      <form  method='GET' class='main--form--wrap'>
        <select name='order' class="form-select me-2">
          <option value="1">최신글</option>
          <option value="2">인기글</option>
          <option value="3">많이본 글</option>
        </select>
        <input type="submit" value='정렬' class="btn btn-secondary btn-sm">
      </form>
      <a type="button" class="btn btn-success" href="{% url 'articles:create' %}">글 생성</a>
    </div>
  
  
    <table class="article--table table table-hover">
      <thead>
        <tr>
          <th scope="col">No</th>
          <th scope="col">제목</th>
          <th scope="col">글쓴이</th>
          <th scope="col">작성시간</th>
          <th scope="col">조회수</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for article in articles %}
        <tr>
          <th scope="row">{{ article.pk }}</th>
          <td>
            <a href="{% url 'articles:detail' article.pk %}">
              {{ article.title }}({{ article.articlecomment_set.all|length }})
            </a>
          </td>
          <td>
            <a href="{% url 'accounts:profile' article.user %}">
            <span class="profile--image--wrap">
            {% if article.user.profile_image %}
            <img class="profile--image" src="{{ article.user.profile_image.url }}" alt="profile-image">
            {% else %}
            <img class="profile--image" src="{% static 'img/cat_01.png' %}" alt="profile">
            {% endif %}    
            </span>
            {{ article.user }}</a>
          </td>
          <td>{{ article.created_at }}</td>
          <td>{{ article.views.all|length }}</td>
        </tr>
    
      {% comment %} <form id="myForm" action="{% url 'articles:detail' article.pk %}" method='POST'>
        {% csrf_token %}
        <a href="{% url 'articles:detail' article.pk %}" id="submitForm">{{ article.title }}</a> 
      </form> {% endcomment %}
    {% endfor %}
    </tbody>
    </table>

    
  </div>
</article>



{% endblock content %}

{% block javascript %}
  <script>
    const submitFormBtn = document.getElementById("submitForm");
    const myForm = document.getElementById("myForm");
    
    submitFormBtn.addEventListener("click", (event) => {
      event.preventDefault(); // 이벤트 전파 중지
      myForm.submit(); // 폼 제출
    });
  </script>
{% endblock javascript %}

articles/templates/articles/update.html
{% extends "base.html" %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'style/articles/create.css' %}">
<link rel="stylesheet" href="{% static 'style/articles/common.css' %}">
{% endblock header %}


{% block content %}
<article class="main--article--container">
  <div class="article--title--wrap">
    <h3 class="article--title">
      <a href="{% url 'articles:index' %}">Community</a>
    </h3>
    <a class="article--list" href="{% url 'articles:tag_cloud' %}">Tag Cloud</a> 
  </div>
  <section class="card--style--wrap">
    <form action="{% url 'articles:update' article.pk %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      {{ imageform.as_p }}
      {% if article.articleimage_set.all %}
      <p>등록된 사진</p>
      {% for image in article.articleimage_set.all %}
          <img src="{{ image.image.url }}" width="200" height="200">
      {% endfor %} 
      {{ delete_images_form.as_p}}
      {% endif %}
      {{ in_image }}
      <button type="submit">수정</button>
    </form></section>
</article>


{% endblock content %}