accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
    path('<int:article_pk>/bookmark/', views.bookmark, name='bookmark'),
    path('<int:article_pk>/comments/<int:comment_pk>/likes/', views.comment_likes, name='comment_likes'),
    path('<int:article_pk>/comments/<int:comment_pk>/dislikes/', views.comment_dislikes, name='comment_dislikes'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('search/', views.search, name='search'),
    # 태그 목록을 볼 수 있는 url 
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    # 태그가 달린 객체들의 목록
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    # path('<int:article_pk>/comments/<int:comment_pk>/update/', views.replyUpdate, name='replyUpdate'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('articles/', include('articles.urls')),
    path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('search/', views.search, name='search'),
    path('region/<region_name>', views.region, name='region'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/likes/', views.post_likes, name='post_likes'),
    path('<int:post_pk>/comment/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_pk>/comment/<int:comment_pk>/likes/', views.comment_likes, name='comment_likes'),
    
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    # 태그가 달린 객체들의 목록
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square.css" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/tenten_favicon_01.png' %}">
    <link rel="stylesheet" href="{% static 'style/common.css' %}">
    <link rel="stylesheet" href="{% static 'style/articles/common.css' %}">
    <link rel="stylesheet" href="{% static 'style/base.css' %}">
    {% block header %}{% endblock header %}
    <title>10.TenTen(TripTopper)</title>
    
    {% block style %}{% endblock style %}
    <style>
    </style>
  </head>
  <body>
    <header class="item header--container position-fixed fixed-top">
      <div class="header--sm--grid--wrap">
        <div class="header--wrap">
          <div class="header--left--wrap">
            <a href="https://port-0-triptopper-f69b2mlhaa9b38.sel4.cloudtype.app/">
              <img class="header--logo--image" src="{% static 'img/triptopper_w_logo_01.png' %}" alt="logo image">
            </a>
            <nav class="header--nav--wrap">
              <ul class="header--nav--flex header--nav">
                <li>
                  <a class="nav--btn" href="{% url 'posts:index' %}">여행일지</a>
                </li>
                <li>
                  <a class="nav--btn" href="{% url 'articles:index' %}">커뮤니티</a>
                </li>
                <li>
                  <a class="nav--btn" href="#10_tenten">만든이들</a>
                </li>
              </ul>
            </nav>
          </div>
          <div class="header--right--wrap">
            {% if user.is_authenticated %}
            <div class="header--login--wrap">
              <a class="header--login" href="{% url 'accounts:profile' user.username%}">
                <span class="nav--btn">{{user}}</span>님 안녕하세요!</a>
              <form action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <input class="btn btn-outline-danger" type="submit" value="log out">
              </form>
            </div>
            {% else %}
            <div class="header--login--wrap">
              <a class="header--login nav--btn" href="{% url 'accounts:login' %}">log in</a>
              <a href="{% url 'accounts:signup' %}" type="button" class="btn btn-outline-success">sign up</a>
            </div>
            {% endif %}
            <div class="header--search--form--wrap">
              <form class="search--form" 
              {% if request.resolver_match.app_name == 'articles' %}
              action='{% url 'articles:search' %}' 
              {% else %}
              action='{% url 'posts:search' %}' 
              {% endif %}
              role='search'>
              <input class="search--input form-control form-control-sm" type="search" placeholder="search" name='q' aria-label="Search">
              <button type="submit"><i class="bi bi-search"></i></button>
            </form>
            </div>
          </div>
        </div>
        {% comment %} max-width 850px {% endcomment %}
        <div class="sm--hader-container">
          <div class="sm--header--search--wrap">
            <form class="search--form sm--search--form" 
              {% if request.resolver_match.app_name == 'articles' %}
                action='{% url 'articles:search' %}' 
              {% else %}
                action='{% url 'posts:search' %}' 
              {% endif %}
              role='search'>
                <input class="sm-search--input form-control form-control-sm" type="search" placeholder="search" name='q' aria-label="Search">
                <button type="submit"><i class="bi bi-search"></i></button>
            </form>
          </div>
          <nav class="sm--nav--wrap">
            <ul class="sm--nav--menu">
              <li>
                <a href="{% url 'posts:index' %}" class="sm--nav__icon--wrap">
                  <i class="bi bi-postcard-heart-fill"></i>
                  <span>여행일지</span>
                </a>
              </li>
              <li>
                <a href="{% url 'articles:index' %}" class="sm--nav__icon--wrap">
                  <i class="bi bi-person-vcard"></i>
                  <span>커뮤니티</span>
                </a>
              </li>
              <li>
                <a href="#10_tenten" class="sm--nav__icon--wrap">
                  <i class="bi bi-people-fill"></i>
                  <span>만든이들</span>
                </a>
              </li>
              <li>
                <div>
                  {% if user.is_authenticated %}
                    <form action="{% url 'accounts:logout' %}" method="POST">
                      {% csrf_token %}
                      <button type="submit" value="log out" class="sm--nav__icon--wrap">
                        <i class="bi bi-box-arrow-right" style='text-align: left'></i>
                        <span class="sm--nav--logout">로그아웃</span>
                      </button>
                    </form>
                    {% else %}
                    <a href="{% url 'accounts:login' %}" class="sm--nav__icon--wrap">
                      <i class="bi bi-box-arrow-in-right"></i>
                      <span>로그인</span>
                    </a>
                  {% endif %}
                </div>
              </li>
              <li>
                <div>
                  {% if user.is_authenticated %}
                    <a href="{% url 'accounts:profile' user.username %}"  class="sm--nav__icon--wrap">
                      <i class="bi-person-video"></i>
                      <span>내 프로필</span>
                    </a>
                    {% else %}
                    <a href="{% url 'accounts:signup' %}"  class="sm--nav__icon--wrap">
                      <i class="bi bi-person-fill-add"></i>
                      <span>회원가입</span>
                    </a>
                  {% endif %}
                </div>
              </li>
            </ul>
          </nav>
          <div class="sm--header--user--hello">
            <span class="nav--btn">{{user}}</span>님 안녕하세요!
          </div>
        </div>
      </div>
    </header>

    <aside class="aside--container">
      <div class="aside--top--wrap z-5">
        <a href="#"><i class="bi bi-airplane-fill"></i></a>
      </div>
    </aside>



    <main class="item main--container main-padding">
    {% block content %}
    {% endblock content %}
    </main>

    <footer id="10_tenten" class="item footer--container">
      <h2 class="footer--title">10조, TenTen</h2>
      <div class="footer--wrap">
        <div class="footer--section--wrap">
          <section class="footer--user--area">
            <div class="footer--section">
              <div class="footer--name--area">
                <h5>박현준</h5>
                <a href="https://together.kakao.com/big-five/summary/13985677">
                  <span class="badge rounded-pill text-bg-warning">BIG 5</span>
                </a>
              </div>
              <ul class="footer--info--area">
                <li>Backend</li>
                <li><a class="link-underline-success success--underline" href="https://github.com/DT-HYUNJUN">
                  https://github.com/DT-HYUNJUN</a></li>
              </ul>
            </div>
          </section>
          <section class="footer--user--area">
            <div class="footer--section">
              <div class="footer--name--area">
                <h5>김민선</h5>
                <a href="https://together.kakao.com/big-five/summary/16366913">
                  <span class="badge rounded-pill text-bg-warning">BIG 5</span>
                </a>
              </div>
              <ul class="footer--info--area">
                <li>Frontend</li>
                <li><a class="link-underline-success success--underline" href="https://github.com/menduck">
                  https://github.com/menduck</a></li>
              </ul>
            </div>
          </section>
          <section class="footer--user--area">
            <div class="footer--section">
              <div class="footer--name--area">
                <h5>최지원</h5>
                <a href="https://together.kakao.com/big-five/summary/795215">
                  <span class="badge rounded-pill text-bg-warning">BIG 5</span>
                </a>
              </div>
              <ul class="footer--info--area">
                <li>Backend</li>
                <li></li>
                <li><a class="link-underline-success success--underline" href="https://github.com/Choi-jw-96">
                  https://github.com/Choi-jw-96</a></li>
                <li><a class="link-underline-warning warning--underline" href="https://support-u-oneday.tistory.com/">
                  https://support-u-oneday.tistory.com/</a></li>
              </ul>
              <br>
            </div>
          </section>
          <section class="footer--user--area">
            <div class="footer--section">
              <div class="footer--name--area">
                <h5>정미영</h5>
                <a href="https://together.kakao.com/big-five/summary/28211106">
                  <span class="badge rounded-pill text-bg-warning">BIG 5</span>
                </a>
              </div>
              <ul class="footer--info--area">
                <li>Frontend</li>
                <li><a class="link-underline-success success--underline" href="https://github.com/qloeo">
                  https://github.com/qloeo</a></li>
              </ul>
            </div>
          </section>
        </div>  
      </div>
      <i class="footer--copyright">copyrightⓒ 2023 All rights reserved by TenTen</i>
    </footer>

    {% block javascript %}
    {% endblock javascript %}
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
test
{% endblock content %}