accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('articles/', include('articles.urls')),
    path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('search/', views.search, name='search'),
    path('region/<region_name>', views.region, name='region'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/likes/', views.post_likes, name='post_likes'),
    path('<int:post_pk>/comment/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_pk>/comment/<int:comment_pk>/likes/', views.comment_likes, name='comment_likes'),
    
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    # 태그가 달린 객체들의 목록
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
]

posts/models.py
import math
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from taggit.managers import TaggableManager
from django.urls import reverse
from django.db import models
from django.conf import settings
from datetime import datetime, timedelta
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
import os
# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    is_new = models.BooleanField(default=False)
    place = models.CharField(max_length=100, default='Unknown')
    region = models.CharField(max_length=50, default='Unknown')
    place_id = models.CharField(max_length=100, default='18577297')
    place_keyword = models.CharField(max_length=100, default='카카오 스페이스닷원')
    start_date = models.DateField(default='2023-05-01')
    end_date = models.DateField(default='2023-05-07')
    rating = models.IntegerField(default=0, validators=[MinValueValidator(1), MaxValueValidator(5)])
    tags = TaggableManager(blank=True)
    
    def get_absolute_url(self):
        return reverse('posts:detail', args=[int(self.id)])
    
    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at
        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.strftime('%Y-%m-%d')


class PostImage(models.Model):
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE)
    
    def post_image_path(instance, filename):
        return f'posts/{instance.post.pk}/{filename}'
           
    image = ProcessedImageField(blank=True,
                                upload_to = post_image_path,
                                # processors= [ResizeToFill(200, 200)],
                                format='JPEG',
                                options={'quality' : 90},
                                null = True,
                                )
    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.name))
            dir_path = os.path.dirname(os.path.join(settings.MEDIA_ROOT, self.image.name))
            if not os.listdir(dir_path):
                os.rmdir(dir_path)
        super(PostImage, self).delete(*args, **kargs)


class PostComment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')


    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.strftime('%Y-%m-%d')

posts/forms.py
from django import forms
from .models import Post, PostComment, PostImage


class PostForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mb-3',
                'placeholder': '제목',
            }
        )
    )
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control mb-3',
                'placeholder': '여행지를 소개해주세요~',
            }
        )
    )
    # image = forms.ImageField(
    #     widget=forms.ClearableFileInput(
    #         attrs={
    #             'class': 'form-control mb-3',
    #         }
    #     ),
    #     required=False
    # )
    place_id = forms.CharField(
        widget=forms.TimeInput(
            attrs={
                'id': 'place-id',
                'class': 'hidden',
            }
        )
    )
    
    place_keyword = forms.CharField(
        widget=forms.TimeInput(
            attrs={
                'id': 'place-keyword',
                'class': 'hidden',
            }
        )
    )
    tags = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder' : '태그 사이에 쉼표를 넣어주세요.'
            }
        )
    )
    rating = forms.IntegerField(
        required=False
    )
    class Meta:
        model = Post
        fields = ('title', 'place', 'region', 'content', 'start_date', 'end_date', 'place_id', 'place_keyword', 'tags', 'rating',)


class PostImageForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('image',)
    image = forms.ImageField(
        label='Image',
        required=False,
        widget=forms.ClearableFileInput(
            attrs={
            'multiple': True,
            'class': 'form-control'
            }
        )
    )


class DeletePostImageForm(forms.ModelForm):
    delete_images = forms.ModelMultipleChoiceField(
        queryset=PostImage.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = PostImage
        fields = []

    def __init__(self, *args, **kwargs):
        instance = kwargs.pop('instance', None)
        super().__init__(*args, **kwargs)
        if instance:
            self.fields['delete_images'].queryset = instance.postimage_set.all()
    
    def save(self, commit=True):
        for image in self.cleaned_data['delete_images']:
            image.delete()

class PostChangeForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mb-3',
                'placeholder': '제목',
            }
        )
    )
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control mb-3',
                'placeholder': '여행지를 소개해주세요~',
            }
        )
    )
    # image = forms.ImageField(
    #     widget=forms.ClearableFileInput(
    #         attrs={
    #             'class': 'form-control mb-3',
    #         }
    #     ),
    #     required=False
    # )
    image = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control mb-3',
            }
        ),
        required=False
    )
    class Meta:
        model = Post
        fields = ('title', 'place', 'region', 'content', 'image', 'start_date', 'end_date', 'rating', )


comment_max = 100
class PostCommentForm(forms.ModelForm):
    content = forms.CharField(
        max_length=comment_max,
        widget=forms.Textarea(
            attrs={
                'id': 'comment-field',
                'class': 'border-0 w-100 comment-form' ,
                'placeholder': '댓글을 남겨보세요',
                'autocomplete': 'off',
                'data-max-length': comment_max,
                'onkeydown': 'resize(this)',
                'onkeyup': 'resize(this)',
                'rows': 1,
            }
        ),
    )
    class Meta:
        model = PostComment
        fields = ('content',)

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'style/posts/index.css' %}">
<link rel="stylesheet" href="{% static 'style/posts/modal.css' %}">
<link rel="stylesheet" href="{% static 'style/posts/detail.css' %}">
{% endblock style %}

{% block content %}
  <main>
    <!--이미지-->
    {% comment %} {% for image in post.postimage_set.all %}
      <img src="{{image.image.url}}" alt="img">
    {% endfor %} {% endcomment %}
    <!--태그-->
    
    <section class="post-content">
      <div class="mb-5">
        {% for image in post.postimage_set.all %}
          {% if forloop.first %}
            <img src="{{image.image.url}}" class="post-img" alt="img">
          {% endif %}
        {% empty %}
          <img src="{% static 'img/noimage.jpg' %}" alt="이미지없음" class="post-img"/>
        {% endfor %}
        {% comment %} {% if post.image %}
        <img src="{{ post.image.url }}" class="post-img" alt="여행이미지">
        {% else %}
        <img src="{% static 'img/noimage.jpg' %}" class="post-img" alt="이미지없음">
        {% endif %} {% endcomment %}
      </div>

      <header class="title-text mb-2">{{ post.title }}</header>
      <article class="d-flex text-nowrap">
        <p class="duration">
          <i class="bi bi-clock-history detail-mark-text">{{ post.start_date }} ~ {{ post.end_date }}</i>
        </p>
        <p class="detail-place">
          <i class="bi bi-geo-alt detail-mark-text">{{ post.region }}</i>
        </p>
        <p>
          <i class="bi bi-star-fill"><span class="detail-mark-text">{{ post.rating }}</span></i>
          <form class="like-form" data-post-id="{{ post.pk }}">
            {% csrf_token %}
            {% if request.user in post.like_users.all %}
            <button type="submit" class="bi bi-heart-fill heart-fill-detail" id="like-btn"></button>
            {% else %}
            <button type="submit" class="bi bi-heart heart-detail" id="like-btn"></button>
            {% endif %}
            <span id="like-count" class="detail-mark-tex">{{ post.like_users.all|length }}</span>
          </form>
        </p>
      </article>
      <article>
        <div class="flex-container">
          <div class="content-container">
            <div>{{ post.content|linebreaksbr }}</div>
            <button type="button" class="border-0 bg-transparent mt-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
              {% if post.postimage_set.all %}
                {% for image in post.postimage_set.all %}
                  {% if forloop.counter <= 4 %}
                    <img src="{{ image.image.url }}" class="multi-image" alt="img">
                  {% else %}
                  <span>...</span>
                  {% endif %}
                {% endfor %}
              {% else %}
              {% endif %}
          </button>

            <div class="tag--box--wrap mt-3">
              {% load taggit_templatetags2_tags %}
              {% get_tags_for_object post as "tags" %}
              {% if tags %}
                {% for tag in tags %}
                  {% if tag.name %}
                  <a class="tag--box" href="{% url 'posts:tagged_object_list' tag.name %}">{{tag.name}}</a>
                  {% endif %}
                {% endfor %}
              {% endif %}
            </div>
          </div>
          <div class="user-profile-container">
            <a href="{% url 'accounts:profile' post.user %}">
            <div class="user-info d-flex">
                {% if post.user.profile_image %}
                <img class="rounded-circle" src="{{ post.user.profile_image.url }}" alt="사용자프로필이미지" />
                {% else %}
                <img src="{% static 'img/user_profile.png' %}" alt="기본프로필이미지" />
                {% endif %}
                <div class="ms-2">
                  <div class='username-text'>{{ post.user }}</div>
                  {% if post.user.mbti %}
                  <div class='userMbit-text'>{{ user_age_range }} {{ post.user.mbti }}</div>
                  {% endif %}
                </div>
              </div>
            </a> 

            {% if request.user != post.user.username %}
              <form class="text-center" id="follow-form" data-user-id="{{ post.user.pk }}">
                {% if request.user in post.user.followers.all %}
                <input type="submit" class="btn btn-success" value="팔로잉" />
                {% else %}
                <input type="submit" class="btn btn-success"  value="팔로워" />
                {% endif %}
              </form>
            {% endif %}
          </div>
        </div>
        
        <hr class="partition-line">
        <div class="position-relative map-detail">
          <div id="map" class="map-detail" data-place="{{ post.place }}"></div>
          <button onclick="panToDetail()" class="position-absolute z-1 fs-3 bg-white rounded-circle pin shadow-lg">
            <i class="bi bi-pin-map-fill"></i>
          </button>
          <button id="modal-button" type="button" class="position-absolute bottom-0 end-0 border-0 z-1" data-bs-toggle="modal" data-bs-target="#mapModal">
            <i class="bi bi-arrows-angle-expand"></i>
          </button>
        </div>
        <div class="map-description d-flex justify-content-between">
          <span class="post-place-text">{{ post.place }}</span>
          <a class="post-place-text" href="https://map.kakao.com/link/to/{{ post.place_id }}" target="_blank">
            <span class="material-symbols-outlined">
              assistant_navigation
            </span>
          </a>
        </div>
      </article>
    </section>
    
    <div class ='content-info'>
      <span>{{ post.updated_at }}</span>
      {% if request.user == post.user %}
        <span class="content-fun"><a href="{% url 'posts:update' post.pk %}">수정</a></span>
        <span class="content-fun"><a onclick="return confirm('게시글을 삭제하시겠습니까?')" href="{% url 'posts:delete' post.pk %}">삭제</a></span>
      {% endif %}
    </div>
      <hr class="partition-line">
    <section class="comments">
      <div class="border-bottom d-flex">
        <span class="mb-3">댓글 {{ comments|length }}</span>
      </div>
      <!-- 댓글 리스트 -->
      <table id="comment-list" class="table">
        <tbody>
          {% for comment in comments %}
            <tr id="comments" {% if request.user == comment.user %}class="bg-body-tertiary"{% endif %}>
              <td class="position-relative">
                <div class="d-flex justify-content-between">
                  <div class="d-flex align-items-start gap-2">
                    <!-- 프로필 사진 -->
                    <div class="border rounded-circle position-relative mt-1 profile-img-sm">
                      {% if comment.user.profile_image %}
                      <a href="{% url 'accounts:profile' comment.user.username %}">
                        <img src="{{ comment.user.profile_image.url }}" alt="{{ comment.user }}" class="rounded-circle profile-img-sm">
                      </a>
                      {% else %}
                      <a href="{% url 'accounts:profile' comment.user.username %}">
                        <div class="position-absolute top-50 start-50 translate-middle">
                          <img src="{% static 'img/user_profile.png' %}" class="profile-img-sm" alt="기본프로필이미지" />
                        </div>
                      </a>
                      {% endif %}
                    </div>
                    <!-- 작성자 / 내용 -->
                    <div>
                      <a href="{% url 'accounts:profile' comment.user.username %}">
                        <span>{{ comment.user }}</span>
                      </a>
                      <p class="m-0">{{ comment.content }}</p>
                      <p class="post-created text-secondary mt-2 mb-0">{{ post.created_at|date:'Y. m. d.  H:i' }}</p>
                    </div>
                  </div>
                  <!-- 삭제 버튼 -->
                  <div class="text-secondary">
                    {% if comment.user == request.user %}
                    <form action="{% url 'posts:comment_delete' post.pk comment.pk %}" method="POST">
                      {% csrf_token %}
                      <button  class="bg-transparent border-0 text-danger comment-delete" type="submit">
                        <div id="comment_delete" class="hidden"><i class="bi bi-x"></i></div>
                      </button>
                    </form>
                    {% endif %}
                  </div>
                </div>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      
      <form id="comment-form" action="{% url 'posts:comment_create' post.pk  %}" method="POST">
        {% csrf_token %}
        <div id="comment-area" class="border rounded-3 p-3">
          <div class="d-flex justify-content-between">
            <span class="mb-2">{{ user.username }}</span>
            <div class="text-body-tertiary">
              <span id="comment-count"></span>
            </div>
          </div>
          {% for field in comment_form %}
            {{ field }}
          {% endfor %}
          <div class="text-end text-body-tertiary">
            <button id="comment-submit" type="submit" class="border-0 bg-transparent text-body-tertiary">등록</button>
          </div>
        </div>
      </form>
    </section>
  </main>
  <hr class="partition-line">
  <!-- 인접 게시물 -->
  <section>
    <div id="container-posts">
      {% for post in posts %}
      <div class="post-item">
        <a href="{% url 'posts:detail' post.pk %}" class="card">
          <div class="position-relative">
            {% for image in post.postimage_set.all %}
              {% if forloop.first %}
                <img src="{{image.image.url}}" class="card-img-top" alt="img">
              {% endif %}
            {% empty %}
            <img
            src="{% static 'img/noimage.jpg' %}"
            alt="이미지없음"
            class="card-img-top"
            />
            {% endfor %}
            <div class="d-flex card-bottom-info card-bottom-hidden">
              <i class="bi bi-star-fill"><span class="mark-text">{{ post.rating }}</span>
              </i>
              <i class="bi bi-chat-dots-fill"><span class="mark-text">{{ post.postcomment_set.count }}</span></i>
            </div>
            <div class="card-top-info-container">
              <div class="d-flex justify-content-between card-top-info mx-1">
                <p class="place ps-1 pe-2">
                  <i class="bi bi-geo-alt">{{ post.region }}</i>
                </p>
                <form class="like-form" data-post-id="{{ post.pk }}">
                  {% csrf_token %}
                  {% if request.user in post.like_users.all %}
                  <button type="submit" class="bi bi-heart-fill" id="like-btn"></button>
                  {% else %}
                  <button type="submit" class="bi bi-heart" id="like-btn"></button>
                  {% endif %}
                </form>
              </div>
            </div>
          </div>

          <div class="card-body">
            <div class="card-user">
              <p>
                {% if post.user.profile_image %}
                <img
                  class="user-profile rounded-circle"
                  src="{{ post.user.profile_image.url }}"
                  alt="사용자프로필이미지"
                />
                {% else %}
                <img
                class="user-profile"
                src="{% static 'img/user_profile.png' %}"
                alt="기본프로필이미지"
                />
              </p>
                {% endif %}
              <span class="username">{{post.user}}</span>
            </div>
            <h6 class="card-title">{{ post.title }}</h6>
            <div class="post-date text-truncate">
              {{ post.created_string }}
            </div>
          </div>
        </a>
      </div>
      {% endfor %}

  </section>

  <div id="my-modal" class="Modal">
    <div class="Modal-content rounded-3">
      <div class="d-flex justify-content-between align-items-center">
        <div>
          <span id="modal-place" class="fw-bold">{{ post.place_keyword }}</span>
          <span id="modal-address">{{ post.place }}</span>
        </div>
        <div class="close">&times;</div>
      </div>
      <div id="modal-content" class="position-relative">
        <button onclick="panTo()" class="position-absolute z-3 fs-3 bg-white rounded-circle pin shadow-lg">
          <i class="bi bi-geo-alt-fill"></i>
        </button>
      </div>
    </div>
  </div>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">{{ post.title }}</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="row gy-4">
            {% for image in post.postimage_set.all %}
              <img src="{{ image.image.url }}" class="col-3" alt="img">
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascript %}
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=46fed7723052d8712b267e8a83ab2fa4&libraries=services"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'js/map.js' %}"></script>
<script src="{% static 'js/map-detail.js' %}"></script>
<script src="{% static 'js/comments.js' %}"></script>
<script src="{% static 'js/like.js' %}"></script>
<script src="{% static 'js/follows.js' %}"></script>
<script src="{% static 'js/card-bottom-info.js' %}"></script>
{% endblock javascript %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'style/posts/create.css' %}">
<link rel="stylesheet" href="{% static 'style/posts/modal.css' %}">
{% endblock style %}

{% block content %}
  <div class="position-relative rounded-3 mt-3 shadow">
    <div id="map" class="map rounded-3"></div>
    <button id="modal-button" type="button" class="position-absolute bottom-0 end-0 z-1 hidden" data-bs-toggle="modal" data-bs-target="#mapModal">
      <i class="bi bi-arrows-angle-expand"></i>
    </button>
  </div>
  
  <form action="{% url 'posts:update' post.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="input-group mb-3 mt-3">
      <span class="input-group-text" id="basic-addon1">여행 만족도</span>
      <div class="form-control pt-0">
        <div id="rating" class="" data-rating="{{ post.rating }}">
          <input id="rating-1" class="rate-input" type="radio" name="rating" value="1" hidden>
          <label class="rate" for="rating-1">☆</label>
          <input id="rating-2" class="rate-input" type="radio" name="rating" value="2" hidden>
          <label class="rate" for="rating-2">☆</label>
          <input id="rating-3" class="rate-input" type="radio" name="rating" value="3" hidden>
          <label class="rate" for="rating-3">☆</label>
          <input id="rating-4" class="rate-input" type="radio" name="rating" value="4" hidden>
          <label class="rate" for="rating-4">☆</label>
          <input id="rating-5" class="rate-input" type="radio" name="rating" value="5" hidden>
          <label class="rate" for="rating-5">☆</label>
          <span id="update" class="ms-3 hidden rate-input">
            <i class="bi bi-arrow-clockwise"></i>
          </span>
        </div>
      </div>
    </div>
    
    {% for field in form %}
      <div class="input-group">
        {% if field.name == 'place' %}
          <input id="place-field" type="text" value="{{ post.place }}" name="place" aria-label="First name" class="form-control mb-3" placeholder="주소" readonly data-bs-toggle="modal" data-bs-target="#addressList" autocomplete="off">
          <input id="region-field" type="text" value="{{ post.region }}" name="region" aria-label="Last name" class="form-control mb-3" placeholder="지역" readonly autocomplete="off">
        {% elif field.name == 'region' %}
        {% elif field.name == 'end_date' %}
        {% elif field.name == 'rating' %}
        {% elif field.name == 'start_date' %}
          {% now "Y-m-d" as today %}
          <input type="date" value="{{ post.start_date|date:'Y-m-d' }}" name="start_date" class="form-control mb-3" placeholder="시작">
          <input type="date" value="{{ post.end_date|date:'Y-m-d' }}" name="end_date" class="form-control mb-3"placeholder="종료">
        {% comment %} {% elif field.name == 'image' %}
          {% if post.image %}
          <div class="input-group">
            <span class="input-group-text mb-3">현재 파일</span>
            <div class="input-group-text mb-3">
              <a class="flex-grow-1 text-truncate" href="{{ post.image.url }}">
                <img style="width: 40px" href="{{ post.image.url }}" src="{{ post.image.url }}" alt="">
              </a>
              <input class="ms-3 form-check-input" type="checkbox" name="image-clear" id="image-clear_id">
              <span class="ms-3">취소</span>
            </div>
          </div>
          {% endif %}
          <input type="file" name="image" class="form-control rounded-2 mb-3" accept="image/*" id="id_image"> {% endcomment %}
        {% else %}
          {{ field }}
        {% endif %}
      </div>
    {% endfor %}
    {{ imageform.as_p }}
    {% if post.postimage_set.all %}
      <p>등록된 사진</p>
    {% for image in post.postimage_set.all %}
      <img src="{{ image.image.url }}" width="200" height="200">
    {% endfor %} 
      {{ delete_images_form.as_p}}
    {% endif %}
    <div class="d-flex gap-3">
      <a href="{% url 'posts:index' %}" class="btn btn-secondary flex-grow-1">취소</a>
      <button class="btn btn-success flex-grow-1">수정 완료</button>
    </div>
  </form>

  <div class="modal fade" id="addressList" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">주소 검색</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <input class="form-control border rounded-0" type="text" list="address-list" id="place_input" autocomplete="off">
        <div class="map-modal-wrap">
          <div id="map-modal"></div>
        </div>
        <div class="modal-body">
          <ol class="list-group list-group-numbered"></ol>
        </div>
      </div>
    </div>
  </div>

  <div id="my-modal" class="Modal">
    <div class="Modal-content rounded-3">
      <div class="d-flex justify-content-between align-items-center">
        <div>
          <span id="modal-place" class="fw-bold">{{ post.place_keyword }}</span>
          <span id="modal-address">{{ post.place }}</span>
        </div>
        <div class="close">&times;</div>
      </div>
      <div id="modal-content" class="position-relative">
        <button onclick="panTo()" class="position-absolute z-3 fs-3 bg-white rounded-circle pin shadow-lg">
          <i class="bi bi-pin-map-fill"></i>
        </button>
      </div>
    </div>
  </div>

{% endblock content %}
  
{% block javascript %}
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=46fed7723052d8712b267e8a83ab2fa4&libraries=services"></script>
{% comment %} <script src="{% static 'js/place-input.js' %}"></script> {% endcomment %}
<script src="{% static 'js/map-modal.js' %}"></script>
<script src="{% static 'js/map-update.js' %}"></script>
<script src="{% static 'js/rating-update.js' %}"></script>
{% endblock javascript %}